name: zenko
version: 1.1.1
appVersion: 1.1.1
kubeVersion: "^1.8.0-0"
description: Zenko is the open source multi-cloud data controller
home: https://www.zenko.io/
icon: https://cdn.jsdelivr.net/gh/scality/Zenko@development/0.9/res/zenko.io-logo-color-cmyk.png
sources:
  - https://github.com/Scality/Zenko
maintainers:
  - name: giacomoguiulfo
  - name: ssalaues
  - name: tmacro
engine: gotpl
tillerVersion: ">=2.8.0"
