apiVersion: v1
kind: Service
metadata:
  name: azure-mock
spec:
  selector:
    name: azure-mock
  clusterIP: None
  ports:
    - name: unused
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: azure-mock-pod
  labels:
    name: azure-mock
spec:
  hostname: devstoreaccount1
  subdomain: azure-mock
  containers:
  - image: tmacro/azure-mock:latest
    args: ['node', 'bin/blob', '-l', '/opt/azurite/folder', '--blobPort', '80']
    name: azurite
    ports:
      - containerPort: 80
