ingress:
  enabled: true

maintenance:
  enabled: true
  accessKey: HEYIMAACCESSKEY
  secretKey: loOkAtMEImASecRetKEy123=
  debug:
    enabled: true
  accessKey: HEYIMAACCESSKEY
  secretKey: loOkAtMEImASecRetKEy123=

prometheus:
  rbac:
    create: true
  serviceAccounts:
    alertmanager:
      name: default
      create: false
    nodeExporter:
      name: default
      create: false
    kubeStateMetrics:
      name: default
      create: false
    pushgateway:
      name: default
      create: false
    server:
      name: default
      create: false

zenko-queue:
  configurationOverrides:
    "offsets.topic.replication.factor": 1 # - replication factor for the offsets topic
    "auto.create.topics.enable": false    # - enable auto creation of topic on the server
    "min.insync.replicas": 1              # - min number of replicas that must acknowledge a write
    "message.max.bytes": "5000000"        # - the largest record batch size allowed
  topics:
    - name: backbeat-gc
      partitions: 1
      replicationFactor: 1
    - name: backbeat-ingestion
      partitions: 1
      replicationFactor: 1
    - name: backbeat-lifecycle-object-tasks
      partitions: 1
      replicationFactor: 1
    - name: backbeat-lifecycle-bucket-tasks
      partitions: 1
      replicationFactor: 1
    - name: backbeat-metrics
      partitions: 1
      replicationFactor: 1
    - name: backbeat-replication
      partitions: 1
      replicationFactor: 1
    - name: backbeat-replication-status
      partitions: 1
      replicationFactor: 1
    - name: backbeat-replication-failed
      partitions: 1
      replicationFactor: 1
    - name: backbeat-sanitycheck
      partitions: 1
      replicationFactor: 1

global:
  orbit:
    endpoint: "http://ciutil-orbit-simulator:4222"
    managerMode: "poll"
    workerMode: "poll"

cloudserver:
  image:
    pullPolicy: Always
  replicaCount: 3
  replicaFactor: 1
  env:
    MPU_TESTING: 'yes'
    PUSH_STATS: 'false'

backbeat:
  replication:
    replicaFactor: 2
  lifecycle:
    conductor:
      cronRule: "0 */1 * * * *"

grafana:
  adminUser: admin
  adminPassword: strongpassword
